version: '3'
services:
  local-listeners-mock:
    build: ./sample-listeners
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"

  webhook-forwarder:
    build: ./teeproxy
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      CLONE_COUNT: ${CLONE_COUNT}
      TARGET_PORT: ${TARGET_PORT}
      LISTEN_PORT: ${LISTEN_PORT}
      TARGET_HOST: ${TARGET_HOST}
  
  rproxy:
    build: ./rproxy
    env_file:
      - .env
    environment:
      FORWARD_FROM_PORT: ${FORWARD_FROM_PORT}
      FORWARD_FROM_HOST: ${FORWARD_FROM_HOST}
      FORWARD_TO_PORT: ${FORWARD_TO_PORT}
      FORWARD_TO_HOST: ${FORWARD_TO_HOST}
    volumes:
      - ./sa-east-1.webhook-fwd.pem:/code/key.pem
